# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyMatch',
                'doc_host': 'https://batmanscode.github.io',
                'git_url': 'https://github.com/batmanscode/pyMatch',
                'lib_path': 'pyMatch'},
  'syms': { 'pyMatch.pymatch': { 'pyMatch.pymatch.add_someone': ('pymatch.html#add_someone', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.count_interests': ('pymatch.html#count_interests', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.database_exists': ('pymatch.html#database_exists', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.database_to_dataframe': ('pymatch.html#database_to_dataframe', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.delete_user': ('pymatch.html#delete_user', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.deta_init': ('pymatch.html#deta_init', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.fetch_all': ('pymatch.html#fetch_all', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.find_by_userid': ('pymatch.html#find_by_userid', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.interestcount_to_dataframe': ( 'pymatch.html#interestcount_to_dataframe',
                                                                                 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.match_interests': ('pymatch.html#match_interests', 'pyMatch/pymatch.py'),
                                 'pyMatch.pymatch.total_users': ('pymatch.html#total_users', 'pyMatch/pymatch.py')}}}
