# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PyMatch',
                'doc_host': 'https://batmanscode.github.io',
                'git_url': 'https://github.com/batmanscode/PyMatch',
                'lib_path': 'PyMatch'},
  'syms': { 'PyMatch.pymatch': { 'PyMatch.pymatch.add_someone': ('pymatch.html#add_someone', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.count_interests': ('pymatch.html#count_interests', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.database_exists': ('pymatch.html#database_exists', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.database_to_dataframe': ('pymatch.html#database_to_dataframe', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.delete_user': ('pymatch.html#delete_user', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.deta_init': ('pymatch.html#deta_init', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.fetch_all': ('pymatch.html#fetch_all', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.find_by_userid': ('pymatch.html#find_by_userid', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.interestcount_to_dataframe': ( 'pymatch.html#interestcount_to_dataframe',
                                                                                 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.match_interests': ('pymatch.html#match_interests', 'PyMatch/pymatch.py'),
                                 'PyMatch.pymatch.total_users': ('pymatch.html#total_users', 'PyMatch/pymatch.py')}}}
